### ISSUE TITLE
HAX Plugin Currently Unavailable via getgrav.org / bin/gpm install hax

### ISSUE THREAD

**Issue by cleverington** [elmsln/grav-plugin-hax#1]
## Issue
1. Tested `1.3.8` and received `Nothing to install` when attempting the `bin/gpm install hax` command.

2. Upgraded, then tested `1.3.10` and received `Nothing to install` when attempting the `bin/gpm install hax` command.

3. Ran `bin/gpm index` command to trace down count on `hax` plugin, but plugin not present.

4. See https://getgrav.org/downloads/plugins -> Search `hax`.

## Notes

https://learn.getgrav.org/advanced/grav-development#theme-plugin-release-process has instructions for 'steps to take' on getting a plugin added to the getgrav.org download list (which matches contents of `bin/gpm index`.

Looks like everything was completely correctly, but it is still in pending status.

Currently open task for getting HAX plugin listed -> https://github.com/getgrav/grav/issues/1811

**Comment by btopro** [comment]
yeah it's all correct just needs to get accepted by them. Not much we can do but wait :)

**Comment by btopro** [comment]
related thread appears to have been closed w/ Grav project owner claiming it is now available on there; try now
