### ISSUE TITLE
HAX installation problem

### ISSUE THREAD

**Issue by withindale** [elmsln/grav-plugin-hax#2]
When the HAX plugin is enabled the editor stops. Webcomponents installed.

My problem is not understanding any of this:
**Simple Usage**
Run bower install inside the GRAV-INSTALL-ROOT/user/plugins/hax
**Better usage**
Symlink over from the GRAV-INSTALL-ROOT/user/plugins/hax to ../../webcomponents/EQUIVALENT-OF-BOWER-COMPONENTS-DIRECTORY. This will make your life a lot easier down the road!
Run something like:
GRAV-INSTALL-ROOT/user/plugins/hax

How to "symlink"?

Thanks for any advice

**Comment by btopro** [comment]
ahh, yeah so bower installation will actually get the assets in place; hax plugin is basically just some wiring but no front end assets to get the job done.
do the following:
```
cd GRAV-INSTALL-ROOT (whatever this is)
mkdir user/webcomponents
cp user/plugins/hax/bower.json user/webcomponents/bower.json
cd user/webcomponents
bower install
```

let me know if that makes sense / helps. We def need better directions here
