### ISSUE TITLE
hax-source.html not found

### ISSUE THREAD

**Issue by heliogabal** [elmsln/grav-plugin-hax#3]
Using v1.4.1 with Admin v1.7.1.

After installing webcomponents and hax plugins, copying bower.json to user/webcomponents and running bower install, I get /user/webcomponents/bower_components/hax-body but there seems to be missing one file from there, as I get this error message when I visit /admin/pages/home: 

> Failed to load resource: the server responded with a status of 404 (Not Found)
> /user/webcomponents/bower_components/hax-body/hax-source.html

On the page, I also don't see the power button, so basically, this doesn't seem to work at all for me.

**Comment by btopro** [comment]
I'll take a look, basically the underlying element vs grav style integration changed slightly so hax-source is named something different. Should be an easy fix, I'll try to get it in today or tomorrow

**Comment by btopro** [comment]
this should be fixed downsteam. It was an issue with the cms-hax element which has now been resolved in master. As right now these things hit master to unpack, give that a try and see now after doing a fresh bower install.

**Comment by heliogabal** [comment]
yep, that solved it. Great, thanks for the fast response, I can't wait to try out this hax magic!

**Comment by btopro** [comment]
@heliogabal been messing w/ it some more this morning. I don't know how to get installers to register in grav w/ latest versions but I've updated to install directions in https://github.com/elmsln/grav-plugin-hax

You'll also most likely need to do a direct git clone of the material -- `git clone https://github.com/elmsln/grav-plugin-hax.git hax` and `git clone https://github.com/elmsln/grav-plugin-webcomponents.git webcomponents`

Please let us know what you find / issues you run into. The Grav integration is more difficult (mostly bc of lack of deep experience with Grav on my part)
