### ISSUE TITLE
Not working with newest GravCMS

### ISSUE THREAD

**Issue by eespro** [elmsln/grav-plugin-hax#4]
Aloha,

I've tried numerous installations with the newest Grav CMS and am unable to get the power button to display

**Comment by btopro** [comment]
hmm bower install and all? is there something unique about 1.4.x your aware of from 1.3.x?

**Comment by jgonyea** [comment]
I have issues with it working on firefox.  I have it functioning on chrome.

**Comment by btopro** [comment]
in the lastest version of Grav that is or just in general w/ FF? FF messing up its related to the polyfill, i wonder if they changed the way I load it in grav or if it's related to newer versions of HAX wanting ShadowDOM to exist (which means a bigger polyfill). If the polyfill is loading on the page could you tweak the plugin (or webcomponents plugin) to load webcomponents.min.js instead of webcomponents-lite.js

**Comment by jgonyea** [comment]
PHP Version 7.0.30 (CentOS 6)
FF Version 60.0.1 (64bit)
Grav v1.4.5 - Admin v1.8.2

**Comment by jgonyea** [comment]
I think your https://github.com/elmsln/grav-plugin-webcomponents/blob/5c53185b08248050fc49fbb37ec770c83b3839d4/webcomponents.php#L222

is miscalling webcomponent vs bower_components.  Changing it doesn't have any effect on Chrome working, nor FF not working, however.

**Comment by jgonyea** [comment]
Webcomponents plugin doesn't add polyfills for admin, and HAX doesn't insert it either.  I have pushed a fix to my repos, and will submit a PR probably late Sunday/ Monday.

**Comment by btopro** [comment]
nice, thanks for tracking this down

**Comment by btopro** [comment]
will need to try latest master in order to see if this is still the issue

**Comment by jgonyea** [comment]
I think you can push a new release for gpm to pick up now that you've merged my code.

**Comment by btopro** [comment]
https://github.com/elmsln/grav-plugin-hax/releases/tag/1.1.0

**Comment by btopro** [comment]
https://github.com/elmsln/grav-plugin-webcomponents/releases/tag/1.1.0 to match

**Comment by btopro** [comment]
is this working now ppl on this thread if you've tested
