### ISSUE TITLE
option to load off CDN

### ISSUE THREAD

**Issue by btopro** [elmsln/grav-plugin-hax#6]
Not sure the best way to do this (maybe @jgonyea has thoughts) but I created prebuilt versions of HAX w/ different breakdowns for cms-hax, wysiwyg-hax, all the elements so that you could just reference a CDN copy and have everything you need (0 build routine).

https://github.com/LRNWebComponents/hax-builds/tree/master/builds is the repo that has the versions

`https://cdn.rawgit.com/LRNWebComponents/hax-builds/0.17.0/builds/cms-hax.html`
`https://cdn.rawgit.com/LRNWebComponents/hax-builds/0.17.0/builds/elements.html`

**Comment by jgonyea** [comment]
Oo, I like the idea of a no-build option.

**Comment by mgifford** [comment]
If there is no way to upload an image, can you make sure that option isn't available?

It would be good if the only options available were those which one could be successful!

**Comment by jgonyea** [comment]
I use an external library for the get-id3 plugin. But your build, @btopro, is more complicated than that one, so I don't know if the same process will work.

**Comment by btopro** [comment]
uploading works in everything not a demo so not sure it would be worth doing but something we can break out into a real repo by itself. Grav should implement uploading files to the file system to match feature parody w/ everything else.

**Comment by mgifford** [comment]
I had trouble uploading to my local Drupal 7 instance.  
<img width="527" alt="screen shot of error" src="https://user-images.githubusercontent.com/116832/40987133-d9b9693c-68b5-11e8-877c-385cfba53238.png">

I think also with the Codepen version.

**Comment by btopro** [comment]
what were you trying to upload int he D7 version (bc that should work). Codepen has no where to upload to, I'm not doubting you or saying it's not a worthy thing to add at least a "there's no backend" message but we're still in the "get people to comprehend all that's possible with this" phase so the code pens and static HTML demos become important imo to have all the capabilities there even if there's no backend for them to be supported

**Comment by btopro** [comment]
@mgifford created a related issue in the hax repo as opposed to the grav integration one (here)
