### ISSUE TITLE
Demo Grav site with Hax

### ISSUE THREAD

**Issue by ElijahLynn** [elmsln/grav-plugin-hax#8]
I'd like to see a demo Grav site with the Hax editor. If one exists already we should put it in the readme and the Grav plugin page. If not, we should make one. Let's discuss this.

**Comment by btopro** [comment]
that sounds like a good idea

**Comment by lucasa** [comment]
Could someone share a working repo?

**Comment by btopro** [comment]
working how so? HAX + Grav or what? it should work and if not please post an issue w/ your steps that it didn't work.

**Comment by btopro** [comment]
@lucasa the repo's latest version now works, there was an issue previously you are correct

**Comment by btopro** [comment]
https://github.com/elmsln/hax-all-the-things
