### ISSUE TITLE
Breaks on update

### ISSUE THREAD

**Issue by RobLui** [elmsln/grav-plugin-hax#9]
Grav & Admin plugin version:
- Grav v1.5.0-beta.2
- Admin v1.8.6

Issue: On updating all the plugins (wich I do to test failures), I noticed that the update on the HAX plugin completely crashes the admin/ normal site interfaces.

Problem: 
Lies in 'hax.php' line 45 perhaps?
bower components are non existent, and there seems to be a required thing from them :)
      -> $assets->addJS($this->getBaseURL() . 'bower_components/webcomponentsjs/' . WebcomponentsPlugin::polyfillLibrary(), array('priority' => 1000, 'group' => 'head'));

Screenshot provided:
![hax](http://share-my-bugs.robbertluit.be/uploads/29298.png "hax")

**Comment by btopro** [comment]
Atools library is now required I believe

**Comment by RobLui** [comment]
That one got updated before the one here :) so that couldn't be the issue I think. 
I think the fault happened because the Webcomponents plugin wasn't updating before the hax plugin, wich caused the missing method error :)

**Comment by btopro** [comment]
Hmm ok, I did just get this installed the other day though you might be right about Bower deps needing to be there

**Comment by btopro** [comment]
so is this a need for web components module to be updated prior to HAX module?

**Comment by RobLui** [comment]
I think so, at least that fixes it :)
